/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_binus_dku_hanback_NewHandler */

#ifndef _Included_com_binus_dku_hanback_NewHandler
#define _Included_com_binus_dku_hanback_NewHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_binus_dku_hanback_NewHandler
 * Method:    ndkPlay
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_binus_dku_hanback_NewHandler_ndkPlay
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_binus_dku_hanback_NewHandler
 * Method:    getSwitchValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_binus_dku_hanback_NewHandler_getSwitchValue
  (JNIEnv *, jclass);

/*
 * Class:     com_binus_dku_hanback_NewHandler
 * Method:    printMsg
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_binus_dku_hanback_NewHandler_printMsg
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
