/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_binus_dku_hanback_LEDHandler */

#ifndef _Included_com_binus_dku_hanback_LEDHandler
#define _Included_com_binus_dku_hanback_LEDHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_binus_dku_hanback_LEDHandler
 * Method:    ndkPlay
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_binus_dku_hanback_LEDHandler_ndkPlay
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
