/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_binus_dku_hanback_Handler */

#ifndef _Included_com_binus_dku_hanback_Handler
#define _Included_com_binus_dku_hanback_Handler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_binus_dku_hanback_Handler
 * Method:    ndkPlay
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_binus_dku_hanback_Handler_ndkPlay
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_binus_dku_hanback_Handler
 * Method:    printMsg
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_binus_dku_hanback_Handler_printMsg
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
