/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_binus_dku_hanback_TextLCDHandler */

#ifndef _Included_com_binus_dku_hanback_TextLCDHandler
#define _Included_com_binus_dku_hanback_TextLCDHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_binus_dku_hanback_TextLCDHandler
 * Method:    printMsg
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_binus_dku_hanback_TextLCDHandler_printMsg
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
